//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace LKReportingSystem.NewCommWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NewComm_Services1Soap", Namespace="http://tempuri.org/")]
    public partial class NewComm_Services1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Transfer_SDH_Burial_SO_To_CommissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessCommissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCommPaidOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCommUnprocessedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NewComm_Services1() {
            this.Url = global::LKReportingSystem.Properties.Settings.Default.LKReportingSystem_NewCommWS_NewComm_Services1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Transfer_SDH_Burial_SO_To_CommissionCompletedEventHandler Transfer_SDH_Burial_SO_To_CommissionCompleted;
        
        /// <remarks/>
        public event ProcessCommissionCompletedEventHandler ProcessCommissionCompleted;
        
        /// <remarks/>
        public event getCommPaidCompletedEventHandler getCommPaidCompleted;
        
        /// <remarks/>
        public event getCommUnprocessedCompletedEventHandler getCommUnprocessedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Transfer_SDH_Burial_SO_To_Commission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Transfer_SDH_Burial_SO_To_Commission(string scmCode, string SONo, string memberCode, System.DateTime SOTrxDate, decimal SONetAmt, System.DateTime SOCommProcessDate, string SOCommProcessUserName) {
            object[] results = this.Invoke("Transfer_SDH_Burial_SO_To_Commission", new object[] {
                        scmCode,
                        SONo,
                        memberCode,
                        SOTrxDate,
                        SONetAmt,
                        SOCommProcessDate,
                        SOCommProcessUserName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Transfer_SDH_Burial_SO_To_CommissionAsync(string scmCode, string SONo, string memberCode, System.DateTime SOTrxDate, decimal SONetAmt, System.DateTime SOCommProcessDate, string SOCommProcessUserName) {
            this.Transfer_SDH_Burial_SO_To_CommissionAsync(scmCode, SONo, memberCode, SOTrxDate, SONetAmt, SOCommProcessDate, SOCommProcessUserName, null);
        }
        
        /// <remarks/>
        public void Transfer_SDH_Burial_SO_To_CommissionAsync(string scmCode, string SONo, string memberCode, System.DateTime SOTrxDate, decimal SONetAmt, System.DateTime SOCommProcessDate, string SOCommProcessUserName, object userState) {
            if ((this.Transfer_SDH_Burial_SO_To_CommissionOperationCompleted == null)) {
                this.Transfer_SDH_Burial_SO_To_CommissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransfer_SDH_Burial_SO_To_CommissionOperationCompleted);
            }
            this.InvokeAsync("Transfer_SDH_Burial_SO_To_Commission", new object[] {
                        scmCode,
                        SONo,
                        memberCode,
                        SOTrxDate,
                        SONetAmt,
                        SOCommProcessDate,
                        SOCommProcessUserName}, this.Transfer_SDH_Burial_SO_To_CommissionOperationCompleted, userState);
        }
        
        private void OnTransfer_SDH_Burial_SO_To_CommissionOperationCompleted(object arg) {
            if ((this.Transfer_SDH_Burial_SO_To_CommissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Transfer_SDH_Burial_SO_To_CommissionCompleted(this, new Transfer_SDH_Burial_SO_To_CommissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessCommission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcessCommission(string entityCode, string scmCode, string propCode, string devCode, string bookNo, int reqNo, decimal unitPrice, decimal unitPriceOR) {
            object[] results = this.Invoke("ProcessCommission", new object[] {
                        entityCode,
                        scmCode,
                        propCode,
                        devCode,
                        bookNo,
                        reqNo,
                        unitPrice,
                        unitPriceOR});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessCommissionAsync(string entityCode, string scmCode, string propCode, string devCode, string bookNo, int reqNo, decimal unitPrice, decimal unitPriceOR) {
            this.ProcessCommissionAsync(entityCode, scmCode, propCode, devCode, bookNo, reqNo, unitPrice, unitPriceOR, null);
        }
        
        /// <remarks/>
        public void ProcessCommissionAsync(string entityCode, string scmCode, string propCode, string devCode, string bookNo, int reqNo, decimal unitPrice, decimal unitPriceOR, object userState) {
            if ((this.ProcessCommissionOperationCompleted == null)) {
                this.ProcessCommissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessCommissionOperationCompleted);
            }
            this.InvokeAsync("ProcessCommission", new object[] {
                        entityCode,
                        scmCode,
                        propCode,
                        devCode,
                        bookNo,
                        reqNo,
                        unitPrice,
                        unitPriceOR}, this.ProcessCommissionOperationCompleted, userState);
        }
        
        private void OnProcessCommissionOperationCompleted(object arg) {
            if ((this.ProcessCommissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessCommissionCompleted(this, new ProcessCommissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCommPaid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal getCommPaid(string projectCode) {
            object[] results = this.Invoke("getCommPaid", new object[] {
                        projectCode});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void getCommPaidAsync(string projectCode) {
            this.getCommPaidAsync(projectCode, null);
        }
        
        /// <remarks/>
        public void getCommPaidAsync(string projectCode, object userState) {
            if ((this.getCommPaidOperationCompleted == null)) {
                this.getCommPaidOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCommPaidOperationCompleted);
            }
            this.InvokeAsync("getCommPaid", new object[] {
                        projectCode}, this.getCommPaidOperationCompleted, userState);
        }
        
        private void OngetCommPaidOperationCompleted(object arg) {
            if ((this.getCommPaidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCommPaidCompleted(this, new getCommPaidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCommUnprocessed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal getCommUnprocessed(string projectCode) {
            object[] results = this.Invoke("getCommUnprocessed", new object[] {
                        projectCode});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void getCommUnprocessedAsync(string projectCode) {
            this.getCommUnprocessedAsync(projectCode, null);
        }
        
        /// <remarks/>
        public void getCommUnprocessedAsync(string projectCode, object userState) {
            if ((this.getCommUnprocessedOperationCompleted == null)) {
                this.getCommUnprocessedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCommUnprocessedOperationCompleted);
            }
            this.InvokeAsync("getCommUnprocessed", new object[] {
                        projectCode}, this.getCommUnprocessedOperationCompleted, userState);
        }
        
        private void OngetCommUnprocessedOperationCompleted(object arg) {
            if ((this.getCommUnprocessedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCommUnprocessedCompleted(this, new getCommUnprocessedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Transfer_SDH_Burial_SO_To_CommissionCompletedEventHandler(object sender, Transfer_SDH_Burial_SO_To_CommissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Transfer_SDH_Burial_SO_To_CommissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Transfer_SDH_Burial_SO_To_CommissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ProcessCommissionCompletedEventHandler(object sender, ProcessCommissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessCommissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessCommissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getCommPaidCompletedEventHandler(object sender, getCommPaidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCommPaidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCommPaidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getCommUnprocessedCompletedEventHandler(object sender, getCommUnprocessedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCommUnprocessedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCommUnprocessedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591