//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKReportingSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://appdev2.lippokarawaci.co.id/LKGeneralWebServices/sqlserverservice.asmx")]
        public string LKReportingSystem_LKGenWS_SQLServerService {
            get {
                return ((string)(this["LKReportingSystem_LKGenWS_SQLServerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.122.2.4/NewCommWebServices/NewComm_Services.asmx")]
        public string LKReportingSystem_NewCommWS_NewComm_Services1 {
            get {
                return ((string)(this["LKReportingSystem_NewCommWS_NewComm_Services1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.122.2.4/BudgetMktWebService/WS_BudgetMarketing.asmx")]
        public string LKReportingSystem_BudgetMktWS_WS_BudgetMarketing {
            get {
                return ((string)(this["LKReportingSystem_BudgetMktWS_WS_BudgetMarketing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.122.2.4/CostContractWebService/WS_CostAndContract.asmx")]
        public string LKReportingSystem_CostContractWS_WS_CostAndContract {
            get {
                return ((string)(this["LKReportingSystem_CostContractWS_WS_CostAndContract"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:55489/WS_OnlineBooking.asmx")]
        public string LKReportingSystem_WS_OnlineBooking_WS_OnlineBooking {
            get {
                return ((string)(this["LKReportingSystem_WS_OnlineBooking_WS_OnlineBooking"]));
            }
        }
    }
}
