//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LKReportingSystemExternal.SIMAWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_SIMASoap", Namespace="http://tempuri.org/")]
    public partial class WS_SIMA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCompanyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProvinceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssetSummaryByCompOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAkuisisiSummaryByCompOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSertipikatAkanJatuhTempoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSertipikatSudahJatuhTempoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssetDocumentChecklistOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusAkuisisiOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertReportParameterOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportParameterOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_SIMA() {
            this.Url = global::LKReportingSystemExternal.Properties.Settings.Default.LKReportingSystemExternal_SIMAWS_WS_SIMA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCompanyCompletedEventHandler GetCompanyCompleted;
        
        /// <remarks/>
        public event GetProvinceCompletedEventHandler GetProvinceCompleted;
        
        /// <remarks/>
        public event GetAssetSummaryByCompCompletedEventHandler GetAssetSummaryByCompCompleted;
        
        /// <remarks/>
        public event GetAkuisisiSummaryByCompCompletedEventHandler GetAkuisisiSummaryByCompCompleted;
        
        /// <remarks/>
        public event GetSertipikatAkanJatuhTempoCompletedEventHandler GetSertipikatAkanJatuhTempoCompleted;
        
        /// <remarks/>
        public event GetSertipikatSudahJatuhTempoCompletedEventHandler GetSertipikatSudahJatuhTempoCompleted;
        
        /// <remarks/>
        public event GetAssetDocumentChecklistCompletedEventHandler GetAssetDocumentChecklistCompleted;
        
        /// <remarks/>
        public event GetStatusAkuisisiCompletedEventHandler GetStatusAkuisisiCompleted;
        
        /// <remarks/>
        public event InsertReportParameterCompletedEventHandler InsertReportParameterCompleted;
        
        /// <remarks/>
        public event GetReportParameterCompletedEventHandler GetReportParameterCompleted;
        
        /// <remarks/>
        public event AuthenticateUserCompletedEventHandler AuthenticateUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCompany", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCompany() {
            object[] results = this.Invoke("GetCompany", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompanyAsync() {
            this.GetCompanyAsync(null);
        }
        
        /// <remarks/>
        public void GetCompanyAsync(object userState) {
            if ((this.GetCompanyOperationCompleted == null)) {
                this.GetCompanyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompanyOperationCompleted);
            }
            this.InvokeAsync("GetCompany", new object[0], this.GetCompanyOperationCompleted, userState);
        }
        
        private void OnGetCompanyOperationCompleted(object arg) {
            if ((this.GetCompanyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompanyCompleted(this, new GetCompanyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProvince", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetProvince() {
            object[] results = this.Invoke("GetProvince", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetProvinceAsync() {
            this.GetProvinceAsync(null);
        }
        
        /// <remarks/>
        public void GetProvinceAsync(object userState) {
            if ((this.GetProvinceOperationCompleted == null)) {
                this.GetProvinceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProvinceOperationCompleted);
            }
            this.InvokeAsync("GetProvince", new object[0], this.GetProvinceOperationCompleted, userState);
        }
        
        private void OnGetProvinceOperationCompleted(object arg) {
            if ((this.GetProvinceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProvinceCompleted(this, new GetProvinceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAssetSummaryByComp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAssetSummaryByComp(string companyID, string provinceID) {
            object[] results = this.Invoke("GetAssetSummaryByComp", new object[] {
                        companyID,
                        provinceID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssetSummaryByCompAsync(string companyID, string provinceID) {
            this.GetAssetSummaryByCompAsync(companyID, provinceID, null);
        }
        
        /// <remarks/>
        public void GetAssetSummaryByCompAsync(string companyID, string provinceID, object userState) {
            if ((this.GetAssetSummaryByCompOperationCompleted == null)) {
                this.GetAssetSummaryByCompOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssetSummaryByCompOperationCompleted);
            }
            this.InvokeAsync("GetAssetSummaryByComp", new object[] {
                        companyID,
                        provinceID}, this.GetAssetSummaryByCompOperationCompleted, userState);
        }
        
        private void OnGetAssetSummaryByCompOperationCompleted(object arg) {
            if ((this.GetAssetSummaryByCompCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssetSummaryByCompCompleted(this, new GetAssetSummaryByCompCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAkuisisiSummaryByComp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAkuisisiSummaryByComp(string companyID) {
            object[] results = this.Invoke("GetAkuisisiSummaryByComp", new object[] {
                        companyID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAkuisisiSummaryByCompAsync(string companyID) {
            this.GetAkuisisiSummaryByCompAsync(companyID, null);
        }
        
        /// <remarks/>
        public void GetAkuisisiSummaryByCompAsync(string companyID, object userState) {
            if ((this.GetAkuisisiSummaryByCompOperationCompleted == null)) {
                this.GetAkuisisiSummaryByCompOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAkuisisiSummaryByCompOperationCompleted);
            }
            this.InvokeAsync("GetAkuisisiSummaryByComp", new object[] {
                        companyID}, this.GetAkuisisiSummaryByCompOperationCompleted, userState);
        }
        
        private void OnGetAkuisisiSummaryByCompOperationCompleted(object arg) {
            if ((this.GetAkuisisiSummaryByCompCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAkuisisiSummaryByCompCompleted(this, new GetAkuisisiSummaryByCompCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSertipikatAkanJatuhTempo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSertipikatAkanJatuhTempo() {
            object[] results = this.Invoke("GetSertipikatAkanJatuhTempo", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSertipikatAkanJatuhTempoAsync() {
            this.GetSertipikatAkanJatuhTempoAsync(null);
        }
        
        /// <remarks/>
        public void GetSertipikatAkanJatuhTempoAsync(object userState) {
            if ((this.GetSertipikatAkanJatuhTempoOperationCompleted == null)) {
                this.GetSertipikatAkanJatuhTempoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSertipikatAkanJatuhTempoOperationCompleted);
            }
            this.InvokeAsync("GetSertipikatAkanJatuhTempo", new object[0], this.GetSertipikatAkanJatuhTempoOperationCompleted, userState);
        }
        
        private void OnGetSertipikatAkanJatuhTempoOperationCompleted(object arg) {
            if ((this.GetSertipikatAkanJatuhTempoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSertipikatAkanJatuhTempoCompleted(this, new GetSertipikatAkanJatuhTempoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSertipikatSudahJatuhTempo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSertipikatSudahJatuhTempo() {
            object[] results = this.Invoke("GetSertipikatSudahJatuhTempo", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSertipikatSudahJatuhTempoAsync() {
            this.GetSertipikatSudahJatuhTempoAsync(null);
        }
        
        /// <remarks/>
        public void GetSertipikatSudahJatuhTempoAsync(object userState) {
            if ((this.GetSertipikatSudahJatuhTempoOperationCompleted == null)) {
                this.GetSertipikatSudahJatuhTempoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSertipikatSudahJatuhTempoOperationCompleted);
            }
            this.InvokeAsync("GetSertipikatSudahJatuhTempo", new object[0], this.GetSertipikatSudahJatuhTempoOperationCompleted, userState);
        }
        
        private void OnGetSertipikatSudahJatuhTempoOperationCompleted(object arg) {
            if ((this.GetSertipikatSudahJatuhTempoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSertipikatSudahJatuhTempoCompleted(this, new GetSertipikatSudahJatuhTempoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAssetDocumentChecklist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAssetDocumentChecklist(string statusAkuisisi) {
            object[] results = this.Invoke("GetAssetDocumentChecklist", new object[] {
                        statusAkuisisi});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssetDocumentChecklistAsync(string statusAkuisisi) {
            this.GetAssetDocumentChecklistAsync(statusAkuisisi, null);
        }
        
        /// <remarks/>
        public void GetAssetDocumentChecklistAsync(string statusAkuisisi, object userState) {
            if ((this.GetAssetDocumentChecklistOperationCompleted == null)) {
                this.GetAssetDocumentChecklistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssetDocumentChecklistOperationCompleted);
            }
            this.InvokeAsync("GetAssetDocumentChecklist", new object[] {
                        statusAkuisisi}, this.GetAssetDocumentChecklistOperationCompleted, userState);
        }
        
        private void OnGetAssetDocumentChecklistOperationCompleted(object arg) {
            if ((this.GetAssetDocumentChecklistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssetDocumentChecklistCompleted(this, new GetAssetDocumentChecklistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStatusAkuisisi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetStatusAkuisisi() {
            object[] results = this.Invoke("GetStatusAkuisisi", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusAkuisisiAsync() {
            this.GetStatusAkuisisiAsync(null);
        }
        
        /// <remarks/>
        public void GetStatusAkuisisiAsync(object userState) {
            if ((this.GetStatusAkuisisiOperationCompleted == null)) {
                this.GetStatusAkuisisiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusAkuisisiOperationCompleted);
            }
            this.InvokeAsync("GetStatusAkuisisi", new object[0], this.GetStatusAkuisisiOperationCompleted, userState);
        }
        
        private void OnGetStatusAkuisisiOperationCompleted(object arg) {
            if ((this.GetStatusAkuisisiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusAkuisisiCompleted(this, new GetStatusAkuisisiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertReportParameter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertReportParameter(string parameter1, string parameter2, string parameter3, string username) {
            object[] results = this.Invoke("InsertReportParameter", new object[] {
                        parameter1,
                        parameter2,
                        parameter3,
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertReportParameterAsync(string parameter1, string parameter2, string parameter3, string username) {
            this.InsertReportParameterAsync(parameter1, parameter2, parameter3, username, null);
        }
        
        /// <remarks/>
        public void InsertReportParameterAsync(string parameter1, string parameter2, string parameter3, string username, object userState) {
            if ((this.InsertReportParameterOperationCompleted == null)) {
                this.InsertReportParameterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertReportParameterOperationCompleted);
            }
            this.InvokeAsync("InsertReportParameter", new object[] {
                        parameter1,
                        parameter2,
                        parameter3,
                        username}, this.InsertReportParameterOperationCompleted, userState);
        }
        
        private void OnInsertReportParameterOperationCompleted(object arg) {
            if ((this.InsertReportParameterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertReportParameterCompleted(this, new InsertReportParameterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportParameter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetReportParameter(int id) {
            object[] results = this.Invoke("GetReportParameter", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportParameterAsync(int id) {
            this.GetReportParameterAsync(id, null);
        }
        
        /// <remarks/>
        public void GetReportParameterAsync(int id, object userState) {
            if ((this.GetReportParameterOperationCompleted == null)) {
                this.GetReportParameterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportParameterOperationCompleted);
            }
            this.InvokeAsync("GetReportParameter", new object[] {
                        id}, this.GetReportParameterOperationCompleted, userState);
        }
        
        private void OnGetReportParameterOperationCompleted(object arg) {
            if ((this.GetReportParameterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportParameterCompleted(this, new GetReportParameterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AuthenticateUser(string username, string password) {
            object[] results = this.Invoke("AuthenticateUser", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string username, string password) {
            this.AuthenticateUserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string username, string password, object userState) {
            if ((this.AuthenticateUserOperationCompleted == null)) {
                this.AuthenticateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUser", new object[] {
                        username,
                        password}, this.AuthenticateUserOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserOperationCompleted(object arg) {
            if ((this.AuthenticateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetCompanyCompletedEventHandler(object sender, GetCompanyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompanyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompanyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetProvinceCompletedEventHandler(object sender, GetProvinceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProvinceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProvinceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetAssetSummaryByCompCompletedEventHandler(object sender, GetAssetSummaryByCompCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssetSummaryByCompCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssetSummaryByCompCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetAkuisisiSummaryByCompCompletedEventHandler(object sender, GetAkuisisiSummaryByCompCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAkuisisiSummaryByCompCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAkuisisiSummaryByCompCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetSertipikatAkanJatuhTempoCompletedEventHandler(object sender, GetSertipikatAkanJatuhTempoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSertipikatAkanJatuhTempoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSertipikatAkanJatuhTempoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetSertipikatSudahJatuhTempoCompletedEventHandler(object sender, GetSertipikatSudahJatuhTempoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSertipikatSudahJatuhTempoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSertipikatSudahJatuhTempoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetAssetDocumentChecklistCompletedEventHandler(object sender, GetAssetDocumentChecklistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssetDocumentChecklistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssetDocumentChecklistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetStatusAkuisisiCompletedEventHandler(object sender, GetStatusAkuisisiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusAkuisisiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusAkuisisiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InsertReportParameterCompletedEventHandler(object sender, InsertReportParameterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertReportParameterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertReportParameterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetReportParameterCompletedEventHandler(object sender, GetReportParameterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportParameterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportParameterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AuthenticateUserCompletedEventHandler(object sender, AuthenticateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591